version: "3"
services:
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        expose: 
            - 5000
        ports:
            - "5000:5000"
        command: npm run dev
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        expose: 
            - 8500
        ports:
            - "8500:3000"
        links:
            - backend
        command: npm run start